"""Add Prompt 11 analytics tables

Revision ID: ecee828ee6ee
Revises: a2d5b0da3fb3
Create Date: 2025-12-08 16:09:39.062703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecee828ee6ee'
down_revision: Union[str, None] = 'a2d5b0da3fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_intents_intent_id'))
        batch_op.drop_index(batch_op.f('idx_payment_intents_provider_tid'))
        batch_op.drop_index(batch_op.f('idx_payment_intents_user_status'))

    op.drop_table('payment_intents')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_idempotency_expires'))
        batch_op.drop_index(batch_op.f('idx_idempotency_key'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('admin_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', sa.String(length=50), nullable=False, comment="Type of flagged object: 'user', 'driver', 'ride', 'booking', 'verification'"))
        batch_op.add_column(sa.Column('object_id', sa.UUID(), nullable=False, comment='UUID of the flagged object'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               comment='Reason for flagging',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'resolved', 'dismissed', name='flag_status'),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_admin_flags_entity'))
        batch_op.drop_index(batch_op.f('idx_admin_flags_reported_by'))
        batch_op.create_index('idx_admin_flags_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_admin_flags_object', ['object_type', 'object_id'], unique=False)
        batch_op.create_index('idx_admin_flags_object_id', ['object_id'], unique=False)
        batch_op.create_index('idx_admin_flags_object_type', ['object_type'], unique=False)
        batch_op.create_index('idx_admin_flags_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_admin_flags_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_flags_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('admin_flags_reviewed_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admin_flags_reported_by_fkey'), type_='foreignkey')
        batch_op.drop_column('flagged_entity_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('flagged_entity_type')
        batch_op.drop_column('reported_by')
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('reviewed_by')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats_reserved', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fare', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, comment='Version field for optimistic locking'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('reserved', 'cancelled', 'completed', name='booking_status'),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index('idx_bookings_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_bookings_passenger_status', ['passenger_id', 'status'], unique=False)
        batch_op.create_index('idx_bookings_ride_status', ['ride_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_passenger_id'), ['passenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_ride_id'), ['ride_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.drop_column('total_price')
        batch_op.drop_column('seats_booked')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='driver_verification_status'), nullable=False))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=False))
        batch_op.alter_column('license_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Encrypted license number - integrate with KMS for encryption/decryption')
        batch_op.alter_column('rating_avg',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('location_last_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Last known latitude - consider PostGIS POINT type for spatial indexing',
               existing_nullable=True)
        batch_op.alter_column('location_last_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Last known longitude - consider PostGIS POINT type for spatial indexing',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_drivers_is_available'))
        batch_op.drop_index(batch_op.f('idx_drivers_verification_status'))
        batch_op.create_index('idx_drivers_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_drivers_vehicle_id', ['vehicle_id'], unique=False)
        batch_op.create_index('idx_drivers_verified', ['verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_rating_avg'), ['rating_avg'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_verified'), ['verified'], unique=False)
        batch_op.create_foreign_key(None, 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('total_rides')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('is_available')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_id', sa.UUID(), nullable=False, comment='User giving the rating'))
        batch_op.add_column(sa.Column('to_user_id', sa.UUID(), nullable=False, comment='User receiving the rating'))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False, comment='Rating value (1-5)'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               comment='Optional review comment',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_ratings_ratee_id'))
        batch_op.drop_index(batch_op.f('idx_ratings_rater_id'))
        batch_op.drop_index(batch_op.f('idx_ratings_score'))
        batch_op.create_index('idx_ratings_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ratings_from_user_id', ['from_user_id'], unique=False)
        batch_op.create_index('idx_ratings_ride_from_user', ['ride_id', 'from_user_id'], unique=False)
        batch_op.create_index('idx_ratings_to_user_id', ['to_user_id'], unique=False)
        batch_op.create_index('idx_ratings_to_user_rating', ['to_user_id', 'rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_ride_id'), ['ride_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_to_user_id'), ['to_user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('ratings_ratee_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ratings_rater_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('score')
        batch_op.drop_column('rater_id')
        batch_op.drop_column('ratee_id')

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_point_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('end_point_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('polyline_main', sa.Text(), nullable=True, comment='Google Maps encoded polyline for main route'))
        batch_op.add_column(sa.Column('polyline_alternates', sa.JSON(), nullable=True, comment="Array of alternative route polylines: [{route: 'encoded_polyline', distance: 1000, duration: 600}]"))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('seats_offered', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seats_booked', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('buffer_seats', sa.Integer(), nullable=False, comment='Optional seats kept aside from immediate booking'))
        batch_op.add_column(sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('start_point_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Starting point latitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('start_point_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Starting point longitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('end_point_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Destination latitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('end_point_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Destination longitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('recurrence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment="Recurring schedule: {pattern: 'daily', days: [1,2,3,4,5], time: '08:00'} or cron-like string",
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'completed', 'cancelled', name='ride_status'),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_rides_departure_time'))
        batch_op.drop_index(batch_op.f('idx_rides_seats_available'))
        batch_op.create_index('idx_rides_driver_status', ['driver_id', 'status'], unique=False)
        batch_op.create_index('idx_rides_start_time', ['start_time'], unique=False)
        batch_op.create_index('idx_rides_status_start_time', ['status', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('rides_vehicle_id_fkey'), type_='foreignkey')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('price_per_seat')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('seats_available')
        batch_op.drop_column('polyline')

    with op.batch_alter_table('telemetry_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='GPS point timestamp - consider partitioning by this column'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS latitude - consider PostGIS POINT type for spatial queries',
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS longitude - consider PostGIS POINT type for spatial queries',
               existing_nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Vehicle speed in km/h',
               existing_nullable=True)
        batch_op.alter_column('bearing',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Direction of travel (0-360 degrees)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_telemetry_recorded_at'))
        batch_op.create_index('idx_telemetry_ride_timestamp', ['ride_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_telemetry_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_points_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_points_ride_id'), ['ride_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_points_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('recorded_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('passenger', 'driver', 'admin', name='user_role'),
               type_=sa.Enum('STUDENT', 'DRIVER', 'ADMIN', 'ORGANIZATION', name='user_roles'),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_created_at'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('cnic')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('seats_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.UUID(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment="Array of photo URLs: ['https://...', 'https://...']",
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vehicles_driver_id'))
        batch_op.drop_index(batch_op.f('idx_vehicles_license_plate'))
        batch_op.drop_constraint(batch_op.f('vehicles_license_plate_key'), type_='unique')
        batch_op.create_index('idx_vehicles_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_vehicles_plate_number', ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=True)
        batch_op.drop_constraint(batch_op.f('vehicles_driver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('license_plate')
        batch_op.drop_column('year')
        batch_op.drop_column('color')

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=False, comment="Document type: 'cnic', 'license', 'passport', 'vehicle_registration'"))
        batch_op.add_column(sa.Column('document_url', sa.String(length=500), nullable=False, comment='URL to uploaded document image (S3 or similar)'))
        batch_op.add_column(sa.Column('ocr_fields', sa.JSON(), nullable=True, comment="OCR extracted fields: {name: 'John Doe', cnic: '12345-1234567-1', dob: '1990-01-01'}"))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True, comment='Overall verification confidence score (0.0 to 1.0)'))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True, comment='Manual review notes from admin'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('face_match_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               comment='Face matching confidence score (0.0 to 1.0)',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status'),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index('idx_verifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_verifications_document_type', ['document_type'], unique=False)
        batch_op.create_index('idx_verifications_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('verifications_reviewed_by_fkey'), type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('cnic_front_url')
        batch_op.drop_column('full_name_on_cnic')
        batch_op.drop_column('cnic_number')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('selfie_url')
        batch_op.drop_column('license_front_url')
        batch_op.drop_column('cnic_back_url')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('license_back_url')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('TOPUP', 'PAYOUT', 'RIDE', name='transaction_type'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', name='transaction_status'),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment="Additional transaction details: {ride_id: 'uuid', payment_method: 'card', gateway_txn_id: 'xxx'}",
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_wallet_transactions_type'))
        batch_op.create_index('idx_wallet_transactions_type', ['type'], unique=False)
        batch_op.create_index('idx_wallet_transactions_wallet_created', ['wallet_id', 'created_at'], unique=False)
        batch_op.create_index('idx_wallet_transactions_wallet_status', ['wallet_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('wallet_transactions_wallet_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('provider_transaction_id')
        batch_op.drop_column('transaction_type')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), nullable=False))
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index('idx_wallets_user_id', ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))
        batch_op.drop_index('idx_wallets_user_id')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', postgresql.ENUM('topup', 'payout', 'ride', name='transaction_type'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wallet_transactions_wallet_id_fkey'), 'wallets', ['wallet_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))
        batch_op.drop_index('idx_wallet_transactions_wallet_status')
        batch_op.drop_index('idx_wallet_transactions_wallet_created')
        batch_op.drop_index('idx_wallet_transactions_type')
        batch_op.create_index(batch_op.f('idx_wallet_transactions_type'), ['transaction_type'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Additional transaction details: {ride_id: 'uuid', payment_method: 'card', gateway_txn_id: 'xxx'}",
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', name='transaction_status'),
               server_default=sa.text("'pending'::transaction_status"),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('type')

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_back_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cnic_back_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('license_front_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selfie_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cnic_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name_on_cnic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cnic_front_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('verifications_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_status'))
        batch_op.drop_index(batch_op.f('ix_verifications_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_created_at'))
        batch_op.drop_index('idx_verifications_user_status')
        batch_op.drop_index('idx_verifications_document_type')
        batch_op.drop_index('idx_verifications_created_at')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status'),
               server_default=sa.text("'pending'::verification_status"),
               existing_nullable=False)
        batch_op.alter_column('face_match_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Face matching confidence score (0.0 to 1.0)',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('review_notes')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('ocr_fields')
        batch_op.drop_column('document_url')
        batch_op.drop_column('document_type')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('license_plate', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vehicles_driver_id_fkey'), 'drivers', ['driver_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_owner_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))
        batch_op.drop_index('idx_vehicles_plate_number')
        batch_op.drop_index('idx_vehicles_owner_id')
        batch_op.create_unique_constraint(batch_op.f('vehicles_license_plate_key'), ['license_plate'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('idx_vehicles_driver_id'), ['driver_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('photos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Array of photo URLs: ['https://...', 'https://...']",
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('owner_id')
        batch_op.drop_column('seats_total')
        batch_op.drop_column('plate_number')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.Enum('STUDENT', 'DRIVER', 'ADMIN', 'ORGANIZATION', name='user_roles'),
               type_=postgresql.ENUM('passenger', 'driver', 'admin', name='user_role'),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('telemetry_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_telemetry_points_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_points_ride_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_points_id'))
        batch_op.drop_index('idx_telemetry_timestamp')
        batch_op.drop_index('idx_telemetry_ride_timestamp')
        batch_op.create_index(batch_op.f('idx_telemetry_recorded_at'), ['recorded_at'], unique=False)
        batch_op.alter_column('bearing',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Direction of travel (0-360 degrees)',
               existing_nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Vehicle speed in km/h',
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPS longitude - consider PostGIS POINT type for spatial queries',
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPS latitude - consider PostGIS POINT type for spatial queries',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polyline', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seats_available', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_per_seat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('rides_vehicle_id_fkey'), 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_rides_status'))
        batch_op.drop_index(batch_op.f('ix_rides_start_time'))
        batch_op.drop_index(batch_op.f('ix_rides_id'))
        batch_op.drop_index(batch_op.f('ix_rides_driver_id'))
        batch_op.drop_index('idx_rides_status_start_time')
        batch_op.drop_index('idx_rides_start_time')
        batch_op.drop_index('idx_rides_driver_status')
        batch_op.create_index(batch_op.f('idx_rides_seats_available'), ['seats_available'], unique=False)
        batch_op.create_index(batch_op.f('idx_rides_departure_time'), ['departure_time'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'completed', 'cancelled', name='ride_status'),
               server_default=sa.text("'open'::ride_status"),
               existing_nullable=False)
        batch_op.alter_column('recurrence',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Recurring schedule: {pattern: 'daily', days: [1,2,3,4,5], time: '08:00'} or cron-like string",
               existing_nullable=True)
        batch_op.alter_column('end_point_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Destination longitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('end_point_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Destination latitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('start_point_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Starting point longitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('start_point_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Starting point latitude - consider PostGIS POINT type',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('base_price')
        batch_op.drop_column('buffer_seats')
        batch_op.drop_column('seats_booked')
        batch_op.drop_column('seats_offered')
        batch_op.drop_column('start_time')
        batch_op.drop_column('polyline_alternates')
        batch_op.drop_column('polyline_main')
        batch_op.drop_column('end_point_address')
        batch_op.drop_column('start_point_address')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratee_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rater_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ratings_rater_id_fkey'), 'users', ['rater_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('ratings_ratee_id_fkey'), 'users', ['ratee_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_ratings_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_ride_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_created_at'))
        batch_op.drop_index('idx_ratings_to_user_rating')
        batch_op.drop_index('idx_ratings_to_user_id')
        batch_op.drop_index('idx_ratings_ride_from_user')
        batch_op.drop_index('idx_ratings_from_user_id')
        batch_op.drop_index('idx_ratings_created_at')
        batch_op.create_index(batch_op.f('idx_ratings_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('idx_ratings_rater_id'), ['rater_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ratings_ratee_id'), ['ratee_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional review comment',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('rating')
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('from_user_id')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('verification_status', postgresql.ENUM('pending', 'verified', 'rejected', name='driver_verification_status'), server_default=sa.text("'pending'::driver_verification_status"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_rides', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_drivers_verified'))
        batch_op.drop_index(batch_op.f('ix_drivers_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_rating_avg'))
        batch_op.drop_index('idx_drivers_verified')
        batch_op.drop_index('idx_drivers_vehicle_id')
        batch_op.drop_index('idx_drivers_user_id')
        batch_op.create_index(batch_op.f('idx_drivers_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_drivers_is_available'), ['is_available'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('location_last_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Last known longitude - consider PostGIS POINT type for spatial indexing',
               existing_nullable=True)
        batch_op.alter_column('location_last_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Last known latitude - consider PostGIS POINT type for spatial indexing',
               existing_nullable=True)
        batch_op.alter_column('rating_avg',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
        batch_op.alter_column('license_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Encrypted license number - integrate with KMS for encryption/decryption')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('verified')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats_booked', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_ride_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_passenger_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))
        batch_op.drop_index('idx_bookings_ride_status')
        batch_op.drop_index('idx_bookings_passenger_status')
        batch_op.drop_index('idx_bookings_created_at')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('reserved', 'cancelled', 'completed', name='booking_status'),
               server_default=sa.text("'reserved'::booking_status"),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('fare')
        batch_op.drop_column('seats_reserved')

    with op.batch_alter_table('admin_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reported_by', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('flagged_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flagged_entity_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('admin_flags_reported_by_fkey'), 'users', ['reported_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('admin_flags_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_admin_flags_status'))
        batch_op.drop_index(batch_op.f('ix_admin_flags_severity'))
        batch_op.drop_index(batch_op.f('ix_admin_flags_object_type'))
        batch_op.drop_index(batch_op.f('ix_admin_flags_object_id'))
        batch_op.drop_index(batch_op.f('ix_admin_flags_id'))
        batch_op.drop_index(batch_op.f('ix_admin_flags_created_at'))
        batch_op.drop_index('idx_admin_flags_status_severity')
        batch_op.drop_index('idx_admin_flags_status_created')
        batch_op.drop_index('idx_admin_flags_object_type')
        batch_op.drop_index('idx_admin_flags_object_id')
        batch_op.drop_index('idx_admin_flags_object')
        batch_op.drop_index('idx_admin_flags_created_at')
        batch_op.create_index(batch_op.f('idx_admin_flags_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_flags_entity'), ['flagged_entity_type', 'flagged_entity_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'resolved', 'dismissed', name='flag_status'),
               server_default=sa.text("'open'::flag_status"),
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason for flagging',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')

    op.create_table('idempotency_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('easypaisa', 'jazzcash', 'card', name='paymentprovider'), autoincrement=False, nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_records_pkey'))
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('idx_idempotency_expires'), ['expires_at'], unique=False)

    op.create_table('payment_intents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('easypaisa', 'jazzcash', 'card', name='paymentprovider'), autoincrement=False, nullable=False),
    sa.Column('intent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('commission', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED', 'REFUNDED', name='paymentstatus'), server_default=sa.text("'PENDING'::paymentstatus"), autoincrement=False, nullable=False),
    sa.Column('provider_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('redirect_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payment_intents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_intents_pkey'))
    )
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payment_intents_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_intents_provider_tid'), ['provider_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_intents_intent_id'), ['intent_id'], unique=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
