// File generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    authDomain: 'sylo-e895e.firebaseapp.com',
    storageBucket: 'sylo-e895e.firebasestorage.app',
    measurementId: 'G-ZR0R5W45N5',
  );

  // NOTE: Register Android/iOS/desktop apps in Firebase Console
  // and update these with platform-specific appIds.
  // Using web credentials as defaults for now.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    storageBucket: 'sylo-e895e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    storageBucket: 'sylo-e895e.firebasestorage.app',
    iosBundleId: 'com.example.sylo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    storageBucket: 'sylo-e895e.firebasestorage.app',
    iosBundleId: 'com.example.sylo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    storageBucket: 'sylo-e895e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDCiEZujCfINIj9uFRZgqRD8GSJgOo3NJ8',
    appId: '1:737107826319:web:11d3ea5dcf57f18e5942fa',
    messagingSenderId: '737107826319',
    projectId: 'sylo-e895e',
    storageBucket: 'sylo-e895e.firebasestorage.app',
  );
}
